teamdigitale/dati-semantic-frontend

src/components/semantic-assets/VocabDetails/VocabDetails.js
src/services/dataConstants.js

Fix typo: vocabolario controllato.

---

public/css/theme-icons.css
src/components/explore/ExploreGrid/ExploreGrid.module.css

[Ankur] - Adds changes for proper grid layout and preloading of the hover image

---

.github/workflows/node.js.yml

- fixes set-output https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Fix github output. See #243.

---

package.json
yarn.lock

This PR does:
1. 
2. 
Fixes #251

Doomrock88 251

---

package.json
src/App.css
src/components/static-content/faq/FaqPage/FaqPage.js
src/components/static-content/project/ProjectBody/ProjectBody.js
src/components/static-content/project/ProjectIndex/ProjectIndex.js
src/components/static-content/project/ProjectPage/ProjectPage.js
yarn.lock

graphic fix
update testing-library/jest-dom to last stable version for fix vulnerability
router for scopri l'iniziativa and f.a.q to catalogo in hero space
This PR does:
1. 
2. 
Fixes #xxx

Graphick fix, vulnerability fix and navigation fix

---

src/components/common/EndSection/EndSection.js
src/components/layout/FooterLinks/FooterLinks.js
src/components/layout/FooterLinks/FooterLinks.test.js
src/components/static-content/project/ProjectBody/ProjectBody.js

This PR does:
1. 
2. 
Fixes #xxx

button in endsection, note legali, page scopri l'iniziatia

---

public/index.html
yarn.lock

test for matomo as analytics
This PR does:
1. 
2. 
Fixes #xxx

active matomo

---

public/index.html
src/components/layout/FooterLinks/FooterLinks.js
src/components/layout/HeaderSlim/HeaderSlim.js
src/components/layout/Main/Main.js
src/components/static-content/legal-notices/legalNotices.js
src/components/static-content/legal-notices/legalNotices.test.js
src/components/static-content/privacy-policy/PrivacyPolicyPage/PrivacyPolicyPage.js
src/services/BreadCrumbsConst.js
src/services/routes.js
yarn.lock

This PR does:
1. 
2. 
Fixes #xxx

Doom rock88 note legali

---

src/components/common/ModifiedOnOrVersion/ModifiedOnOrVersion.js
src/components/layout/FooterLinks/FooterLinks.js
src/components/search/AssetTypeChip/AssetTypeChip.js
src/components/search/Pagination/Pagination.js
src/components/semantic-assets/AssetDetails/summary/AssetDetailsSummary.js
src/components/static-content/legal-notices/legalNotices.js

1. Aggiunta pagina "Note Legali"
2. #402
3. #401
4. #400
5. #399
@CreaIstat

Notelegali

---

.env
package.json
src/components/semantic-assets/AssetDetails/summary/AssetDetailsButtons.js
yarn.lock

1. Test Bugfix porting
@CreaIstat

Redirect error

---

src/components/semantic-assets/AssetDetails/metadata/AssetIriRow.js
src/components/semantic-assets/AssetDetails/metadata/CommonMetadataGroup.js

This PR does:
1. Fix porting bootstrap and react 18
@CreaIstat

Bug Fix Porting v3

---

package-lock.json
src/components/semantic-assets/AssetDetails/metadata/AssetIriRow.js
src/components/semantic-assets/AssetDetails/metadata/MetadataRow.js
src/components/semantic-assets/AssetDetails/metadata/OntologyMetadata.js
src/components/semantic-assets/AssetDetails/metadata/VocabularyMetadata.js
yarn.lock

1. vulnerability test and concetti principali fix
@CreaIstat

vulnes test and concetti principali fix

---

src/components/common/IntroSection/IntroSection.js
src/components/search/AssetTypeFilter/AssetTypeFilter.test.js
src/components/search/FilterPanel/FilterModalMobile.jsx
src/components/search/MultiCheckBoxFilter/MultiCheckBoxFilter.js
src/components/search/MultiCheckBoxFilter/MultiCheckBoxFilter.test.js
src/components/search/MultiSelectChips/MultiSelectChips.jsx
src/components/search/Pagination/Pagination.js
src/components/search/PatternFilter/PatternFilter.js
src/components/search/SearchPage/SearchPage.js
src/components/search/SearchPage/partials/ResultCount.jsx
src/components/search/SearchResultItem/SearchResultItem.js

fix(general): remove all buttons from filters and fix accessibility

---

src/components/search/FilterPanel/FilterModalMobile.jsx
src/components/search/PatternFilter/PatternFilter.js
src/components/search/SearchPage/SearchPage.js

fix(general): fix modal filter and pattern input on mobile

---

src/components/search/SearchResultItem/SearchResultItem.js

fix(search): add control on themes cards

---

src/components/common/IntroSection/IntroSection.js
src/components/search/SearchResultItem/SearchResultItem.js

Fix padding breadcrumbs for mobile and overflow on uri in cards
@CreaIstat

fix(general): fix minor bugs

---

src/components/search/MultiSelectChips/MultiSelectChips.jsx
src/components/search/RightsHoldersFilter/RightsHoldersFilter.js

Fix title of multi-select filters for Safari browser
@CreaIstat

fix(search): fix title filters for safari

---

src/components/common/ModalChangeOrientation/ModalChangeOrientation.jsx
src/components/common/ModalChangeOrientation/useModalOrientation.jsx
src/components/search/MultiSelectChips/MultiSelectChips.jsx
src/components/search/RightsHoldersFilter/RightsHoldersFilter.js
src/components/search/SearchPage/SearchPage.js
src/components/search/SearchResultItem/SearchResultItem.js
src/components/semantic-assets/AssetDetails/summary/AssetDetailsButtons.js

Resolve minor bugs

---

.github/PULL_REQUEST_TEMPLATE.md
README.md

This PR includes some bug fixes to README.md and PULL_REQUEST_TEMPLATE.md files.
Fixes #515, Fixes #517, Fixes #518 
CC: @Clou-dia, @mauropratesi

Fixing some bugs on readme and PR template files

---

src/components/explore/ExploreByCategory/ExploreByCategory.js
src/components/layout/ScrollToTop/ScrollToTop.js
src/components/search/MultiSelectChips/MultiSelectChips.jsx
src/components/search/RightsHoldersFilter/RightsHoldersFilter.js
src/components/search/SearchResultItem/SearchResultItem.module.css

fix(general): resolve minor bugs v2

---

CODE_OF_CONDUCT.md

Inserted the code of conducted as written into dati-semantic-backend repo.
This PR does: adding the code of conduct into the repository, extracted from the "dati-semantic-backend" one.
@Clou-dia @mauropratesi

Adding the Code of Conduct

---

src/components/search/SearchResultItem/SearchResultItem.js

Switched the tag `<a>` on cards of search list into `<div>`
Fixes #504

fix(search): fix hover state on chips of cards

---

src/App.test.js
src/global-bootstrap-italia.js

chore(library): fix bootstrap-italia import

---

public/index.html
src/components/static-content/validatore/Validatore.css
src/components/static-content/validatore/Validatore.js
src/global-bootstrap-italia.js

fix(general): remove scroll from zenscroll and fix accordion import

---

src/App.css
src/components/common/BreadCrumbs/BreadCrumbs.js
src/components/common/FilterContext/context.jsx
src/components/common/IntroSection/IntroSection.js
src/components/explore/ExplorePage/ExplorePage.test.js
src/components/search/SearchResultItem/SearchResultItem.js
src/components/static-content/validatore/Validatore.css
src/components/static-content/validatore/Validatore.js
src/global-bootstrap-italia.js

fix(general): fix zenscroll and import collapse

---

src/components/common/BreadCrumbs/BreadCrumbs.js

fix(breadcrumbs): fix breadcrumbs after navigation refactor

---

src/global-bootstrap-italia.js

chore(general): fix import all bootstrap js

---

package.json
src/components/layout/HeaderMainMenu/HeaderMainMenu.js
src/components/layout/Main/Main.js
src/components/static-content/validatore/Validatore.css
src/components/static-content/validatore/Validatore.js
src/components/static-content/validatore/Validatore.test.js
src/components/static-content/validatore/partials/ValidatoreResult.js
src/services/BreadCrumbsConst.js
src/services/routes.js
yarn.lock

Updated "Validatore semantico" in "Validatore metadati" as requested in the document  "Requisiti_Validatore dei metadati delle risorse semantiche per schema.gov.it v2.0"
NO ISSUE LINKED
@ndc-istat

cr(validatore): update validatore metadati v2

---

src/components/layout/HeaderMainMenu/HeaderMainMenu.js
src/components/static-content/validatore/Validatore.js
src/components/static-content/validatore/partials/ValidatoreResult.js

fix(validatore): fix responsive view

---

src/components/static-content/validatore/partials/ValidatoreResult.js

fix(validatore): fix footer position v2
